routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/backend', 'BackendController@index')->name('backend.root');
Route::get('/home', 'BackendController@index')->name('home');
Route::get('/getusers', 'BackendController@getusers')->name('getusers');
Route::get('/deluser/{id}', 'BackendController@deluser')->name('deluser');


Auth::routes(['verify'=>true]);

Route::resource('/batch', 'Backend\BatchController');
Route::get('/loadbatch', 'Backend\BatchController@loadbatch')->name('loadbatch');

Route::resource('/courses', 'Backend\CourseController');
Route::get('/getsemcourse/{id}', 'Backend\CourseController@getsemcourse')->name('getsemcourse');
Route::get('/getmycourse/{id}', 'Backend\CourseController@getmycourse')->name('getmycourse');



Route::resource('/students', 'Backend\StudentController');
Route::get('/studentdetails/{id}', 'Backend\StudentController@details')->name('students.details');
Route::get('/showsectionstd/{id}', 'Backend\StudentController@showsectionstd')->name('students.showsectionstd');
Route::get('/setmarks/{session}/{section}/{mycourse}/{exam}', 'Backend\StudentController@setmarks')->name('setmarks');


Route::resource('/guard', 'Backend\GuardController');
Route::post('/saveguard/{id}', 'Backend\GuardController@saveguard')->name('saveguard');



Route::resource('/section', 'Backend\SectionController');
Route::post('/section/{year}', 'Backend\SectionController@savesection')->name('savesection');
Route::get('/getsection/{session}', 'Backend\SectionController@getsection')->name('getsection');
Route::get('/loadsectioninfo/{session}', 'Backend\SectionController@loadsectioninfo')->name('loadsectioninfo');

Route::get('/display/{section}', 'Backend\SectionController@display')->name('getmysection');

Route::resource('/semesters', 'Backend\SemesterController');

Route::resource('/sessions', 'Backend\SessionController');

Route::resource('/marks', 'Backend\ResultController');

Route::get('/getallmarks/{stid}/{sem}','Backend\ResultController@getallmarks')->name('getallmarks');

Route::resource('/teachers', 'Backend\TeacherController');

Route::resource('/staffs', 'Backend\StaffController');
Route::get('/staffpost', 'Backend\StaffController@staffpost');


Route::resource('/exams', 'Backend\ExamController');

Route::resource('/examsroutine', 'Backend\ExamRotuineController');
Route::get('/examsubjects/{session}/{exam}', 'Backend\ExamRotuineController@examsubjects');



Route::get('{path}', 'BackendController@index')->where('path' , '([A-z\d-\/_.]+)?')->name('backend.root');

// Route::get('/home', 'HomeController@index')->name('home');

app/Result.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Result extends Model
{
    
    public function exam()
    {
        return $this->belongsTo('App\Exam');
    }
}

app/Http/Controllers/Backend/ResultController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller; 
use App\Result;
use App\Student;
use App\Session;
use App\Course;
use App\Exam;

class ResultController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    } 

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $counter = count($request->markssetter);
        // dd($counter);
// dd($request->all());
        for($i=0; $i<$counter; $i++){
            
            if($request->myid[$i]){
                $getid = $request->myid[$i];
                $result = Result::where('id',$getid)->first();
            }else{
                $result = new Result();
                $result->course_id = $request->course;
                $result->exam_id = $request->exam;
                $result->session_id = $request->session;
                $result->student_id = $request->student[$i];
            }
            if(isset($request->markssetter[$i])){
                $result->marks = $request->markssetter[$i];
            }else{
                $result->marks = 'Abs';
            }
            // dd($result);
            $result->save();
        }

        return redirect()->back();


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // return $id;
    }

    public function getallmarks($stdid, $sem)
    {        
        // $getallcourse =  Course::where('semester_id', $sem)->get();
        // $getallexam =  Exam::all();

        $batch = Student::findOrFail($stdid)->batch_id;
        $sessionslug = $batch.$sem;

        $getsession = Session::where('slug',$sessionslug)->first()->id;

        $myresult = Result::where(['student_id'=>$stdid , 'session_id'=>$getsession])->with('exam')->get();

        return $myresult;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/pages/result/editresult.blade.php
@extends('backend.laramaster')
@section('content')
            <div class="row justify-content-center mt-4">
            <div class="col-md-12">
                <div class="card card-primary card-outline">
              <div class="card-header">
                <h3 class="card-title">Section List for <b>{{$info->batch->enrolled_year}}</b> batch <b>{{$info->semester->semester}}</b> for <u>Subject:: {{$course->subject}}</u> <b>{{$section->section_name}} Section</b></h3>
                
                <div class="card-tools">
        

                </div>

              </div>
              <!-- /.card-header -->

              <div class="card-body table-responsive pt-10">

                <div class="row">
                <form action="{{route('marks.store')}}" method="post">
                @csrf()

                @foreach($students as $student)
                    <div class="col-lg-12 col-12">
                   
                        <!-- small box -->
                        <div class="small-box">
                            <div class="inner">
                                <h4>Roll:{{$student->roll_no}}</h4>
                                <p>{{$student->person->fname}}</p>
                                 <input type="hidden" name="student[]" value={{$student->id}}>
                                 <input type="hidden" name="exam" value={{$exam->id}}>
                                 <input type="hidden" name="course" value={{$course->id}}>
                                 <input type="hidden" name="session" value={{$session}}>
                       
                                    @foreach($marks as $mark)
                                        @if($mark[0]->student_id == $student->id)
                                        <input type="text" name="markssetter[]" id="markssetter"  value= "{{$mark[0]->marks}}" class="form-control" placeholder="Enter Marks.">
                                        <input type="hidden" name="myid[]" value={{$mark[0]->id}}>                                
                                        @endif
                                        
                                    @endforeach
                            </div>               
                        </div>
                       
                    </div>
                    @endforeach

                    <button type="submit">Submit/Update</button>
                   
                </form>
                </div>
            </div>

            </div>
            </div>

        </div>
        
@endsection

resources/views/backend/pages/result/setresult.blade.php
@extends('backend.laramaster')
@section('content')
            <div class="row justify-content-center mt-4">
            <div class="col-md-12">
                <div class="card card-primary card-outline">
              <div class="card-header">
                <h3 class="card-title">Section List for <b>{{$info->batch->enrolled_year}}</b> batch <b>{{$info->semester->semester}}</b> for <u>Subject:: {{$course->subject}}</u> <b>{{$section->section_name}} Section</b></h3>
                
                <div class="card-tools">
        

                </div>

              </div>
              <!-- /.card-header -->

              <div class="card-body table-responsive pt-10">

                <div class="row">
                <form action="{{route('marks.store')}}" method="post">
                @csrf()

                @foreach($students as $student)
                    <div class="col-lg-12 col-12">
                   
                        <!-- small box -->
                        <div class="small-box">
                            <div class="inner">
                                <h4>Roll:{{$student->roll_no}}</h4>
                                <p>{{$student->person->fname}}</p>
                                 <input type="hidden" name="student[]" value={{$student->id}}>
                                 <input type="hidden" name="exam" value={{$exam->id}}>
                                 <input type="hidden" name="course" value={{$course->id}}>
                                 <input type="hidden" name="session" value={{$session}}>
                       
                                 <input type="text" name="markssetter[]" id="markssetter"  class="form-control" placeholder="Enter Marks.">
                                
                            </div>               
                        </div>
                       
                    </div>
                    @endforeach

                    <button type="submit">Submit/Update</button>
                   
                </form>
                </div>
            </div>

            </div>
            </div>

        </div>
        
@endsection